<?php

return [
    'signs-of-autism-in-toddlers' => [
        'slug' => 'signs-of-autism-in-toddlers',
        'pillar' => 'autism',
        'title' => 'Signs of autism in toddlers',
        'meta_title' => 'Signs of Autism in Toddlers (1–3 Years)',
        'meta_desc' => 'Simple signs of autism in toddlers (children about 1–3 years). This is not a diagnosis. When parents should ask for help.',
        'excerpt' => 'A toddler is a child about 1 to 3 years old. This list is for noticing, not for naming the child yourself.',
        'mins' => 5,
        'related' => ['speech-delay-vs-autism', 'what-happens-in-an-autism-assessment', 'late-talker-when-to-worry'],
        'sections' => [
            ['h2' => 'What is a toddler?', 'html' => '<p>A <strong>toddler</strong> is a young child who has started walking, usually about <strong>1 to 3 years</strong> old.</p><p>This page cannot say “your child has autism”. Only a qualified doctor or psychologist can do that after a proper check.</p>'],
            ['h2' => 'Signs to notice', 'html' => '<ul><li>Does not look when you call their name</li><li>Does not point to show you something (only pulls you for a biscuit)</li><li>Talks late, or only repeats TV lines</li><li>Little pretend play (feeding a doll, talking on a toy phone)</li><li>Very upset if the routine changes</li><li>Covers ears, walks on toes, or flaps hands when excited</li></ul>'],
            ['h2' => 'What should I do next?', 'html' => '<p>See a child doctor (paediatrician, a doctor for children). Ask for a hearing check. A speech-language pathologist can watch play and talking. Bring phone videos from home.</p>'],
        ],
        'faqs' => [
            ['q' => 'My toddler hugs me a lot. Can it still be autism?', 'a' => 'Yes. Many autistic children love their parents. Autism is about talking, play, and change, not a lack of love.'],
            ['q' => 'He spoke and then stopped. What now?', 'a' => 'Get a check soon, for hearing and for development. Do not wait for a “phase”.'],
        ],
    ],
    'speech-delay-vs-autism' => [
        'slug' => 'speech-delay-vs-autism',
        'pillar' => 'speech-language',
        'title' => 'Speech delay vs autism',
        'meta_title' => 'Speech Delay vs Autism: Simple Difference',
        'meta_desc' => 'Late talking is not always autism. Simple difference for parents, and what to do next.',
        'excerpt' => 'Late talking and autism can look similar. They are not always the same.',
        'mins' => 5,
        'related' => ['signs-of-autism-in-toddlers', 'when-to-start-speech-therapy', 'late-talker-when-to-worry'],
        'sections' => [
            ['h2' => 'Simple difference', 'html' => '<p><strong>Speech delay</strong> (late or unclear talking): the child usually wants to connect with you, but words or sounds are late.</p><p><strong>Autism</strong> (a difference in talking, play, and feeling the world): the child may also talk late, but they may not point to share, pretend, or enjoy back-and-forth play in the usual way.</p><p>Many children have late talking without autism. Some have both. A hearing check is needed in both cases.</p>'],
            ['h2' => 'Questions to ask yourself', 'html' => '<ul><li>Does my child point to show me something interesting?</li><li>Do they look at me to share a laugh?</li><li>Do they pretend, even a little?</li></ul>'],
        ],
        'faqs' => [
            ['q' => 'If they look in my eyes, it cannot be autism?', 'a' => 'Some autistic children do look, especially at family. One sign is not enough to say yes or no.'],
            ['q' => 'Should we stop the second language?', 'a' => 'Usually no. Keep the languages you actually speak at home.'],
        ],
    ],
    'adhd-symptoms-in-children' => [
        'slug' => 'adhd-symptoms-in-children',
        'pillar' => 'adhd',
        'title' => 'ADHD signs in school-age children',
        'meta_title' => 'ADHD Signs in School Children: A Simple Guide',
        'meta_desc' => 'Simple ADHD signs at home and school. Not the same as a naughty child. What to tell a doctor.',
        'excerpt' => 'ADHD (attention deficit hyperactivity disorder, difficulty with attention, sitting still, or waiting) should show at home and at school, not only with one teacher.',
        'mins' => 5,
        'related' => ['adhd-and-speech-delay', 'adhd-support-in-dehradun', 'sensory-processing-issues-in-kids'],
        'sections' => [
            ['h2' => 'What does ADHD look like?', 'html' => '<ul><li><strong>Attention:</strong> loses things, misses instructions, unfinished work</li><li><strong>Sitting still:</strong> leaves the seat, fidgets, hums</li><li><strong>Waiting:</strong> blurts answers, grabs, cannot wait in a line</li></ul><p>A child can have one of these more than the others. Quiet “dreamy” children, especially girls, are often missed.</p>'],
            ['h2' => 'What to bring to the clinic', 'html' => '<p>School remarks, sleep times, and real examples (“cannot start homework unless I sit there”). If talking or handwriting is also hard, say so.</p>'],
        ],
        'faqs' => [
            ['q' => 'Can a quiet girl have ADHD?', 'a' => 'Yes. Some children are not noisy. They just miss what the teacher said.'],
            ['q' => 'Is it ADHD or too much mobile?', 'a' => 'Phones can make attention worse. If the problem is old and happens at home and school, still get a proper check.'],
        ],
    ],
    'sensory-processing-issues-in-kids' => [
        'slug' => 'sensory-processing-issues-in-kids',
        'pillar' => 'occupational-therapy',
        'title' => 'When the world feels too loud or too itchy',
        'meta_title' => 'Sensory Issues in Children: A Simple Guide',
        'meta_desc' => 'Sensory means how the body feels sound, touch, and movement. Simple guide for parents.',
        'excerpt' => 'Sensory (how the body feels sound, touch, and movement) problems can look like “bad behaviour”.',
        'mins' => 4,
        'related' => ['occupational-therapy-for-autism', 'adhd-symptoms-in-children', 'helping-child-with-special-needs-at-home'],
        'sections' => [
            ['h2' => 'What does sensory mean?', 'html' => '<p><strong>Sensory</strong> means how the body feels sound, touch, clothes, food, and movement. Some children cover ears at loud noise. Some chew shirts or crash into sofas. Many do both. This is common in autism and ADHD.</p>'],
            ['h2' => 'What not to do', 'html' => '<p>Do not force a child into a huge noisy wedding “for practice” with no plan. Slow steps work better.</p>'],
        ],
        'faqs' => [
            ['q' => 'Is picky eating always sensory?', 'a' => 'No. If the child is losing weight, see a doctor first.'],
        ],
    ],
    'when-to-start-speech-therapy' => [
        'slug' => 'when-to-start-speech-therapy',
        'pillar' => 'speech-language',
        'title' => 'When to start speech therapy',
        'meta_title' => 'When to Start Speech Therapy',
        'meta_desc' => 'Start speech therapy when talking or understanding is stuck. You do not need to wait for school.',
        'excerpt' => 'You do not need to wait for a failed nursery interview.',
        'mins' => 4,
        'related' => ['late-talker-when-to-worry', 'speech-therapy-in-dehradun', 'speech-delay-vs-autism'],
        'sections' => [
            ['h2' => 'When should we start?', 'html' => '<p>Start when talking or understanding is stuck. Examples: almost no real words at 2 years; a 4-year-old others cannot understand; stammering (getting stuck on words) that lasts many months; a child who cannot ask for what they need.</p>'],
        ],
        'faqs' => [
            ['q' => 'How many sessions per week?', 'a' => 'Often 1–2, plus daily practice at home. Clinic time without home practice helps little.'],
        ],
    ],
    'what-happens-in-an-autism-assessment' => [
        'slug' => 'what-happens-in-an-autism-assessment',
        'pillar' => 'autism',
        'title' => 'What happens in an autism check',
        'meta_title' => 'What Happens in an Autism Assessment',
        'meta_desc' => 'An autism assessment is a careful check: questions, play, and sometimes hearing. Simple steps for parents.',
        'excerpt' => 'An assessment (careful check) is not a trap. It is a structured look at your child.',
        'mins' => 5,
        'related' => ['autism-assessment-in-dehradun', 'signs-of-autism-in-toddlers', 'speech-delay-vs-autism'],
        'sections' => [
            ['h2' => 'What happens?', 'html' => '<p>People will ask about growing up, sleep, and talking. They will watch play. They may ask the playschool to fill a form. They may check hearing. Home videos help, because clinic behaviour can be different.</p>'],
            ['h2' => 'Who gives the name “autism”?', 'html' => '<p>Usually a child doctor, a psychiatrist (a doctor for thoughts, feelings, and behaviour), or a psychologist (a specialist who tests and talks, and does not give medicine). A therapy centre can write what they see in talking and daily skills. That does not replace a medical diagnosis (official name).</p>'],
        ],
        'faqs' => [
            ['q' => 'Will you judge my parenting?', 'a' => 'No. Tell the truth about screens and routine. It helps the plan.'],
        ],
    ],
    'occupational-therapy-for-autism' => [
        'slug' => 'occupational-therapy-for-autism',
        'pillar' => 'occupational-therapy',
        'title' => 'Daily-skill therapy for autistic children',
        'meta_title' => 'Occupational Therapy for Autistic Children',
        'meta_desc' => 'OT means help with eating, dressing, writing, and feeling comfortable. How it can help autistic children.',
        'excerpt' => 'OT (help with daily skills) is the practical layer: body, clothes, food, and school sitting.',
        'mins' => 4,
        'related' => ['sensory-processing-issues-in-kids', 'helping-child-with-special-needs-at-home', 'signs-of-autism-in-toddlers'],
        'sections' => [
            ['h2' => 'Why is OT used?', 'html' => '<p>If a child cannot sit long enough to learn a word, or melts down putting on a school belt, talking practice alone will stall. OT works on feeling safe in the body and doing daily tasks.</p>'],
            ['h2' => 'What does progress look like?', 'html' => '<p>Fewer fights over socks. Using a spoon. A haircut with a plan. A few extra minutes in class. These are real gains.</p>'],
        ],
        'faqs' => [
            ['q' => 'Is OT the same as physiotherapy?', 'a' => 'No. Physiotherapy (help with walking, strength, and movement) is different. OT is more about daily tasks and how the body feels the world.'],
        ],
    ],
    'adhd-and-speech-delay' => [
        'slug' => 'adhd-and-speech-delay',
        'pillar' => 'adhd',
        'title' => 'ADHD and late talking together',
        'meta_title' => 'ADHD and Speech Delay: A Simple Guide',
        'meta_desc' => 'A child can have ADHD and late talking together. Simple explanation for parents.',
        'excerpt' => 'A child who “does not listen” may not have understood the sentence.',
        'mins' => 4,
        'related' => ['adhd-symptoms-in-children', 'when-to-start-speech-therapy', 'speech-delay-vs-autism'],
        'sections' => [
            ['h2' => 'Why both can happen', 'html' => '<p>ADHD can make it hard to hold a long instruction. Late language can make the instruction unclear in the first place. Teachers may call it “not listening”. A speech check tests understanding without guessing.</p>'],
        ],
        'faqs' => [
            ['q' => 'Fix ADHD first or talking first?', 'a' => 'Usually both, in small steps. Waiting for perfect attention before starting talking help wastes a year.'],
        ],
    ],
    'ocd-like-behaviours-in-autistic-children' => [
        'slug' => 'ocd-like-behaviours-in-autistic-children',
        'pillar' => 'autism',
        'title' => 'Repeating and routines: is it OCD?',
        'meta_title' => 'Autism Routines vs OCD: Simple Difference',
        'meta_desc' => 'Lining toys and same routines are often part of autism, not always OCD. Simple guide for parents.',
        'excerpt' => 'OCD (unwanted fears and repeated actions to feel safe) is not the same as loving sameness in autism.',
        'mins' => 5,
        'related' => ['signs-of-autism-in-toddlers', 'helping-child-with-special-needs-at-home', 'sensory-processing-issues-in-kids'],
        'sections' => [
            ['h2' => 'Simple difference', 'html' => '<p>Many autistic children need sameness to feel safe: the same cup, the same road. That is often part of autism.</p><p><strong>OCD</strong> is different: the child has scary unwanted thoughts and does rituals (like washing again and again) to reduce fear. They are often upset by the thought.</p>'],
            ['h2' => 'When to see a mental-health doctor', 'html' => '<p>If rituals take over the day, or the child is terrified something bad will happen unless they repeat, see a child psychiatrist (doctor for thoughts, feelings, and behaviour) or psychologist. Do not copy “exposure” videos (forcing the child to face the fear) at home. Speech and daily-skill therapy can help with autism routines and senses. They are not an OCD medicine clinic.</p>'],
        ],
        'faqs' => [
            ['q' => 'Should I stop all lining of toys?', 'a' => 'Do not make it a fight. Use lining as a start for play (“the cars are waiting”) rather than banning the only calming activity.'],
        ],
    ],
    'helping-child-with-special-needs-at-home' => [
        'slug' => 'helping-child-with-special-needs-at-home',
        'pillar' => 'special-needs',
        'title' => 'Help at home',
        'meta_title' => 'Helping a Child with Extra Needs at Home',
        'meta_desc' => 'Simple home tips: two goals, short talking, sleep, and siblings.',
        'excerpt' => 'Clinic time is short. Home is where skills stick.',
        'mins' => 5,
        'related' => ['when-to-start-speech-therapy', 'occupational-therapy-for-autism', 'special-education-for-children-dehradun'],
        'sections' => [
            ['h2' => 'Pick two goals', 'html' => '<p>This month: asking for water, and a calmer bedtime. That is enough. Write them on the fridge so the whole house follows the same plan.</p>'],
            ['h2' => 'How to talk at home', 'html' => '<p>Sit at their level. Talk about what they are doing. Pause. Do not fire ten questions. Celebrate trying, not only perfect words. Cut solo screen time.</p>'],
        ],
        'faqs' => [
            ['q' => 'Should we hire a full-time helper at home?', 'a' => 'Not as the first step. First teach asking, waiting a little, and a tiny routine. A helper who does everything can slow independence.'],
        ],
    ],
    'speech-therapy-in-dehradun' => [
        'slug' => 'speech-therapy-in-dehradun',
        'pillar' => 'speech-language',
        'title' => 'What speech therapy is',
        'meta_title' => 'What Speech Therapy Is: A Simple Parent Guide',
        'meta_desc' => 'Speech therapy helps late talking, unclear speech, and stammering. What sessions usually cover.',
        'excerpt' => 'Speech therapy is help with talking, understanding, and being understood.',
        'mins' => 3,
        'related' => ['when-to-start-speech-therapy', 'late-talker-when-to-worry', 'autism-assessment-in-dehradun'],
        'sections' => [
            ['h2' => 'Who it is for', 'html' => '<p>Late talkers, unclear speech, stammering (getting stuck on words), and children with autism or ADHD who need a way to ask for things.</p>'],
            ['h2' => 'What a visit usually looks like', 'html' => '<p>The therapist watches play and talking, checks how much the child understands, and gives you a few home goals. Hearing should already be checked, or booked soon after.</p>'],
        ],
        'faqs' => [
            ['q' => 'Is one session enough?', 'a' => 'No. Skills grow with practice at home. Clinic time shows you what to practise.'],
        ],
    ],
    'autism-assessment-in-dehradun' => [
        'slug' => 'autism-assessment-in-dehradun',
        'pillar' => 'autism',
        'title' => 'How an autism check usually starts',
        'meta_title' => 'How an Autism Assessment Usually Starts',
        'meta_desc' => 'Where to start for an autism check. What a therapy centre can do and what a doctor does.',
        'excerpt' => 'You can start help while you wait for a specialist date.',
        'mins' => 4,
        'related' => ['what-happens-in-an-autism-assessment', 'speech-therapy-in-dehradun', 'signs-of-autism-in-toddlers'],
        'sections' => [
            ['h2' => 'A simple order', 'html' => '<p>1) Child doctor. 2) Hearing check. 3) Talking and play check with a speech-language pathologist. A formal diagnosis (official name) is with a doctor or psychologist. You do not have to freeze all help until that paper arrives.</p>'],
        ],
        'faqs' => [
            ['q' => 'Do therapy centres give disability certificates?', 'a' => 'No. Those follow government medical boards. A therapy report is not the same document.'],
        ],
    ],
    'adhd-support-in-dehradun' => [
        'slug' => 'adhd-support-in-dehradun',
        'pillar' => 'adhd',
        'title' => 'Support for ADHD',
        'meta_title' => 'ADHD Support for Children: A Simple Guide',
        'meta_desc' => 'ADHD help: routine, talking, daily skills. Therapy does not replace a doctor’s advice about medicine.',
        'excerpt' => 'Listening, language, and school-ready habits can be practised. Medicine is a doctor’s decision.',
        'mins' => 3,
        'related' => ['adhd-symptoms-in-children', 'adhd-and-speech-delay', 'speech-therapy-in-dehradun'],
        'sections' => [
            ['h2' => 'What therapy can work on', 'html' => '<p>If ADHD comes with late talking, or with handwriting or sensory trouble (the body finding sound, touch, or clothes hard), practical sessions can help. Therapy does not diagnose with tablets and does not prescribe medicine.</p>'],
        ],
        'faqs' => [
            ['q' => 'Can someone talk to the school?', 'a' => 'With your permission, a short written list of tips is often most useful. Ask at the visit.'],
        ],
    ],
    'late-talker-when-to-worry' => [
        'slug' => 'late-talker-when-to-worry',
        'pillar' => 'speech-language',
        'title' => 'Late talker: when to worry',
        'meta_title' => 'Late Talker: When to Worry',
        'meta_desc' => 'A late talker is a child whose words come later than expected. Simple red flags and what to do next.',
        'excerpt' => 'Word count matters. Pointing, play, and understanding matter more than family stories.',
        'mins' => 4,
        'related' => ['when-to-start-speech-therapy', 'speech-delay-vs-autism', 'autism-and-hearing'],
        'sections' => [
            ['h2' => 'When to worry more', 'html' => '<p>Worry more if there is no pointing to share, poor understanding, no pretend play, or lost words. A child with some words who points, pretends, and follows “give the shoes” is a different picture from a child who only recites rhymes.</p><p>Do three things: hearing check, less solo screen time, and a speech visit if red flags sit with late words.</p>'],
        ],
        'faqs' => [
            ['q' => 'Boys talk late, true?', 'a' => 'A small group difference is not a reason to ignore a child who is not communicating.'],
        ],
    ],
    'autism-and-hearing' => [
        'slug' => 'autism-and-hearing',
        'pillar' => 'hearing',
        'title' => 'Autism and hearing',
        'meta_title' => 'Autism and Hearing Tests: A Simple Guide',
        'meta_desc' => 'Not turning to name can be autism, hearing, or both. Why a hearing test still matters.',
        'excerpt' => 'Not turning to name can be autism, a hearing problem, or both. Test; do not assume.',
        'mins' => 3,
        'related' => ['late-talker-when-to-worry', 'signs-of-autism-in-toddlers', 'speech-therapy-in-dehradun'],
        'sections' => [
            ['h2' => 'Why test hearing?', 'html' => '<p>An autistic child may hear the fan and ignore their name because social attention is hard. They may also have fluid in the ear. Only a test sorts it.</p>'],
        ],
        'faqs' => [
            ['q' => 'Do noise headphones replace a hearing test?', 'a' => 'No. Headphones can help comfort. They do not check the ear.'],
        ],
    ],
    'special-education-for-children-dehradun' => [
        'slug' => 'special-education-for-children-dehradun',
        'pillar' => 'special-needs',
        'title' => 'Extra learning support',
        'meta_title' => 'Special Education for Children: A Simple Guide',
        'meta_desc' => 'Special education means teaching the way this child learns. Small steps and pictures, not a warehouse away from family.',
        'excerpt' => 'Extra learning support means small steps and pictures, not a warehouse away from family.',
        'mins' => 3,
        'related' => ['helping-child-with-special-needs-at-home', 'autism-assessment-in-dehradun', 'adhd-support-in-dehradun'],
        'sections' => [
            ['h2' => 'What we mean', 'html' => '<p><strong>Special education</strong> means teaching in small steps, with pictures, and measuring tiny gains. It can support school-readiness. It is not a promise of exam marks.</p>'],
        ],
        'faqs' => [
            ['q' => 'Will this replace school?', 'a' => 'Usually it supports school. Do not pull a child out without a serious reason and a better plan.'],
        ],
    ],
];
